-include openmrnpath.mk
ifndef OPENMRNPATH
OPENMRNPATH := $(realpath ../../openmrn)
endif


SUBDIRS= \
        webinar_app_1  \
        webinar_app_2_stack  \
        webinar_app_3_connection  \
        webinar_app_4_consumer  \
        webinar_app_5_snip_static_data  \
        webinar_app_6_cdi_config  \
        webinar_app_7_blinker_consumer  \
        webinar_app_8_gpio_pins  \
        webinar_app_9_repeated_consumers  \


include $(OPENMRNPATH)/etc/recurse.mk
